#b#cff0000ff*Kondisi menang di antara peserta#nb#nc
 - Kamu dinyatakan menang jika HP lawan mencapai 0.
#b#cff0000ff* Kondisi seri di antara peserta#nb#nc
 - Jika pertarungan tidak selesai dalam waktu 10 menit, maka akan dinyatakan seri.

#b#cff0000ff*  Kondisi menang untuk Guild peserta#nb#nc
 - Guild dengan anggota pemenang paling banyak akan menang.
#b#cff0000ff* Kondisi seri untuk Guild peserta#nb#nc
 - Jika kedua Guild punya jumlah anggota pemenang yang sama, the Siege akan dinyatakan seri.
