#b#cff0000ff* Peraturan Dasar#nb#nc
 - Pertarungan 1 lawan 1 antara 2 karakter.
 - Buff dan Party Skill akan dilepas saat pemain memasuki Arena.
 - Para Penonton dan para Peserta tidak dapat saling berinteraksi.
 - 11 Anggota dari setiap Guild dapat ikut serta.
 - Jika tidak ada lawan kau akan menang secara otomatis.
 - Red Chip akan diberikan kepada pemenang perorangan dan keada keseluruhan Guild yang menang.

#b#cffff0000 Kamu tidak bisa mendaftar 1vs1 Guild Siege dan Guild Siege pada saat yang bersamaan.#nb#nc
