#b#cff0000ff* Rewards#nb#nc
* Winning guild receives 10 Guild War Champion Box which contains a Dark Devil's Cloak, 1 for each member of the team and 5 for any 5 members of your Guild! After a set period, you'll have to fight again to earn the right to wear them. 
* Each participant of the winning guild receives the 1st in Guild War Compensation box, which contains 189 Red Chips, 1 Guild War Participation Cloak and 1 Guild Siege Coin.
* Winning guild receives the Winner's Dignity buff for 1 week:

    HP +10%
    Parry +5%
    Melee Block +5%
    Range Block +5% 

#b#cffff0000* Note: Make sure you have enough free space in your guild warehouse for rewards before entering the Guild Siege!#nb#nc
* The second-place guild participants receive the 2nd in Guild War Compensation box, which contains 54 Red Chips, 1 Guild War Participation Cloak and 1 Guild Siege Coin.
* The third-place guild participants receive the 3rd in Guild War Compensation box, which contains 27 Red Chips, 1 Guild War Participation Cloak and 1 Guild Siege Coin.
* Every other participant gets a Guild War Participation Box, which includes 1 Guild Siege Coin, a Guild War Participation Cloak as well as a certain number of Red Chips.
* When a guild wins two times in a row they will receive the Guild War Champion Box (Double). This box contains:

    2 Guild Siege Coins
    1 Guild War Compensation Cloak
    189 Red Chips 

And will receive the Radiant Glory buff for 1 week:

    HP +20%
    Parry +10%
    Melee Block +10%
    Range Block +10% 


