#b#cff0000ff* Basic Rules#nb#nc
 - Battle lasts for 30 minutes.
 - Parties and Buff will be cancelled.
 - Item trading is disabled 5 minutes before combat.
 - 5 members from each Guild join.
 - A new member enters replaces a defeated guild member.
 - Defeated members move to The end of The line.
 - Each member has 3 "lives".

#b#cffff0000* Players cannot join Guild seige and 1vs1 Guild Siege at the same time.#nb#nc
