#b#cff0000ff Participation Info #nb#nc
* Application Period :  (Sun) 00:00~ (Sat) 17:00
* Location : 1st sub server
* Qualification
 - Only the guild master apply for Guild Seige
 - The Guild more than Guild Level 20
 - The Guild Member  more than Level 30
 - Guild Master(Or Kingpin) should be added to the participant list.
 - Top 8 Guilds with the highest application fee will join(Before the time for application)
* Time Table
 - 18:00  Entry starts  
 - 18:10  Entry ends
 - 18:11  Battle starts 

#b#cffff0000* Guild Seige begins if more than 2 Guilds applied.#nb#nc
