#b#cff0000ff participation Info #nb#nc
* Time Limit for application : from (Sun) 00:00 to (Sat) 18:30
* Battle Area : First sub server of each server cluster
* Qualifications
 - Only GuildMaster apply for the participation
 - Guild Level more than 20
 - GuildMember Level more than 30
 - GuildMaster(KingPin) should be added to the entry
 - Top 8 highest bid join (Before application period ends)
* Time Table
 - 19:30  Entry Starts 
 - 19:40  Entry Ends
 - 19:45  Battle Starts  
 - 20:15  Battle Ends
#b#cffff0000¡Ø GuildSeige will be held in case at least 3 Guilds apply for GuildSeige.#nb#nc