#b#cff0000ff* Peraturan Dasar#nb#nc
 - Pertarungan bertahan selama 30 Menit.
 - Parties dan Buff akan dibatalkan.
 - Pertukaran Item akan dimatikan 5 menit sebelum pertarungan.
 - Setiap pertarungan bertahan dalam 10 Menit.
 - 5 Anggota dari setiap guild ikut serta.
 - Anggota baru masuk menggantikan anggota guild yang kalah.
 - Anggota yang kalah di pindahkan ke garis akhir.
 - Setiap anggota mempunyai 3 "nyawa".

#b#cffff0000* Pemain tidak dapat mengikuti Guild seige dan 1vs1 Guild Siege pada saat bersamaan.#nb#nc
