#b#cff0000ff* Kemenangan#nb#nc
#b#cff0000ff* Prioritas#nb#nc
1. Poin final tertinggi
2.Jumlah terbesar dari kesempatan hidup dari karakter yang selamat
3. Level rata-rata terendah dari karakter yang selamat
#b#cff0000ff* Perolehan Poin#nb#nc
Kalahkan musuh (+2)
#b#cff0000ff* Perolehan Poin Bonus (Bisa Tumpang tindih)#nb#nc
 - Mengalahkan musuh yang belum dikalahkan oleh karakter sebelumnya (+1)
 - Mengalahkan musuh oleh Guild Master (+1)
 - Mengalahkan Defender (+1)
 - Mengalahkan musuh ketika kesempatan hidup karakter 0 (+1)
 - Untuk setiap kesempatan hidup karakter yang selamat (+1)
