#b#cff0000ff Basic Rules #nb#nc
 - 1 on 1 battle between the players in the same queue.
 - As entered, Party Skills and Buff Skills effect will be removed.
 - No interactions between the battle area and audience area.
 - Total eleven Guild Members can join.
 - In case of no opponent, you will win by default
 - RedChip will be given both individul winning and aslo Guild's winning.

#b#cffff0000* You cannot apply both GuildSeige and 1:1 GuildSeige at the same time.#nb#nc
