#b#cff0000ff* Partisipasi#nb#nc
* Waktu aplikasi: Minggu 00:00 sampai Sabtu 12:00
* Tempat pertarungan: Server Channel 1
* Kondisi
 - Ketua Guild
 - Level Guild yang dibutuhkan: Level 20+
 - Level Anggota Guild yang dibutuhkan: 30+
 - Ketual Guild atau Kingpin harus ikut serta.
 - 8 Guild yang membayar tertinggi akan diberikan hak masuk ke Guild Siege.
* Jadwal
 - 13:30  Aplikasi diterima
 - 13:10  Periode aplikasi diterima
 - 13:15  Pertarungan dimulai
 - 13:45 Pertarungan berakhir
#b#cffff0000* Guild Siege hanya akan dimulai jika ada 3 atau lebih Guild yang diterima.#nb#nc
