#b#cff0000ff*Info Partisipasi.#nb#nc
* Periode Aplikasi :  (Minggu) 00:00~ (Sabtu) 17:00
* Lokasi : sub server 1
* Kualifikasi
 - Hanya ketua Guild yang dapat mendaftar Guild Sieges.
 - Guild harus minimal berlevel 20.
 - Anggota Guild harus lebih dari level 30.
 - Ketua Guild or Kingpins harus disertakan ke daftar partisipasi.
 - 8 teratas yang membayar Aplication Fee tertinggi akan diterima ke Guild Siege.
* Tabel waktu
 - 18:00  Pemasukan dimulai
 - 18:10  Pemasukan berakhir
 - 18:11  Pertarungan dimulai

#b#cffff0000Guild Siege dimulai jika 2 atau lebih Guild telah mendaftar.#nb#nc
