#b#cff0000ff Basic Rules #nb#nc
 - 30min for the battle.
 - Party & Buff Skill will be removed.
 - No interactions are allowed between battle area and observation area
 - Join the battle with avdance party with 5 members and maximum 10 members can join.
 - In case the character dies, then the player in following queue joins 
 - Dead character will be moved to the last of the list
 - Each character has chance to revive 6 times#nb#nc
#b#cff0000ff* GuildMaster : Get bouns point in case taking down opponent
* Defender(Except for GuildMaster) : Get bonus point in case taking down#nb#nc

#b#cffff0000¡Ø You can't apply for GuildSeige and 1to1 GuildSeige at the same time.#nb#nc