#b#cff0000ff The condition of win between individuals #nb#nc
 - In case your opponent's HP goes to 0.
#b#cff0000ff The condition of draw between individuals #nb#nc
 - In case the battle is not done within time.

#b#cff0000ff The condition of win between Guilds #nb#nc
 - The Guild has more number of winning Guild Memebers
#b#cff0000ff The condition of draw between Guilds #nb#nc
 - In case both Guilds have the same number of winning Guild Members
