#b#cff0000ff Winning #nb#nc
#b#cff0000ff Priority #nb#nc
1. The highest final point
2. The most amount of revival chance of survived characters
3. The lowest average level of survived characters
#b#cff0000ff Point Gaining #nb#nc
Defeating the enemy (+2)
#b#cff0000ff Bonus Point Gaining (Overlapping is possible) #nb#nc
 - Killing the enemy who was not defeated by the character before (+1)
 - Killing the enemy by Guild Master (+1)
 - Killing Defender (+1)
 - Killing the enemy when the revival chance of the character is 0 (+1)
 - To every revival chance of survived characters (+1)
