#b#cff0000ff* Participation#nb#nc
* Application Time 
 EN -> Sunday 00:00 to Wednesday 18:30 and Thursday 00:00 to Saturday 18:30
 US -> Sunday 01:00 to Thursday 01:30 and Thursday 06:00 to Saturday 20:30
* All times in UTC
* Combat Place : Server Channel 1
* Conditions
 - Guild Leader
 - Required Guild Level: Level 20+
 - Required Guild Member Level: 30+ 
 - Guild Leader or Kingpin must join.
 -The 8 highest paying guilds will be granted entry to the Guild Siege. 

* EN Schedule 
<All times in UTC>
 [Wednesday / Saturday]
 - 19:30  Begin Entry
 - 19:40  End Entry
 - 19:45  Guild Siege Start
 - 19:15  Guild Siege End

* US Schedule 
<All times in UTC>
 [Thursday]
 - 02:30 Begin Entry
 - 02:40 End Entry
 - 02:45 Guild Siege Start
 - 03:15 Guild Siege End

 [Saturday]
 - 21:30 Begin Entry
 - 21:40 End Entry
 - 21:45 Guild Siege Start
 - 22:15 Guild Siege End

#b#cffff0000* Guild Siege will only begin if 3 or more Guilds are accepted.#nb#nc