#cffff0000 Bienvenue dans le monde fabuleux de Flyff !

#cffffdd66
Le continent de Madrigal a connu beaucoup de conflits…
mais est désormais en quête d'harmonie, d'entraide et de paix.

Comme l'aurait souhaité Rhisis,
respectez et aidez les autres habitants de Madrigal.

Bonne aventure !

#cffff0000 Les responsables de communauté sont disponibles pour vous aider au mieux.
#cffff0000 Vous pouvez accéder au support à l'adresse #cffffdd66http://fr.cs.gpotato.eu/HelpDesk
#cffff0000 ou visiter notre site #cffffdd66flyff.gpotato.eu