#cffC6E2FF#b#uWelcome to FlyFF Gold!#nb#nu

We hope you enjoy your stay in Madrigal.  
For the latest events, contests, and general information about FlyFF, check out our Discord located at:
#u#bhttps://discord.gg/nU4n8N2#nb#nu

To contact a Game Master regarding in-game issues:
#cff0099CC#b#uhttps://flyff.zendesk.com/hc/en-us/requests/new#nb#nu#nc

Happy FlyFFing,
#bThe FlyFF Game Master Team#nb






